repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black